/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IctTrainingRouteImport } from './routes/ict-training'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as ApiArewagateAirtimeRouteRouteImport } from './routes/api/arewagate/airtime.route'
import { Route as ApiArewagateBvnVerificationRouteRouteImport } from './routes/api/arewagate/bvn-verification.route'
import { Route as ApiArewagateCacVerificationRouteRouteImport } from './routes/api/arewagate/cac-verification.route'
import { Route as ApiArewagateNinSlipNormalRouteRouteImport } from './routes/api/arewagate/nin-slip-normal.route'
import { Route as ApiArewagateNinSlipPremiumRouteRouteImport } from './routes/api/arewagate/nin-slip-premium.route'
import { Route as ApiArewagateNinVerificationRouteRouteImport } from './routes/api/arewagate/nin-verification.route'
import { Route as ApiArewagateNinVerificationSlipRouteRouteImport } from './routes/api/arewagate/nin-verification-slip.route'
import { Route as ApiArewagateScratchCardRouteRouteImport } from './routes/api/arewagate/scratch-card.route'
import { Route as ApiArewagateTransactionsRouteRouteImport } from './routes/api/arewagate/transactions.route'
import { Route as ApiArewagateWalletRouteRouteImport } from './routes/api/arewagate/wallet.route'
import { Route as ApiArewagateDataDetailsRouteImport } from './routes/api/arewagate/data/details'
import { Route as ApiArewagateDataPurchaseRouteImport } from './routes/api/arewagate/data/purchase'
import { Route as ApiArewagateJambDetailsRouteImport } from './routes/api/arewagate/jamb/details'
import { Route as ApiArewagateJambPurchaseRouteImport } from './routes/api/arewagate/jamb/purchase'
import { Route as ApiArewagateScratchCardBalanceRouteRouteImport } from './routes/api/arewagate/scratch-card/balance.route'
import { Route as ApiArewagateUtilityBillsPayRouteRouteImport } from './routes/api/arewagate/utility-bills/pay.route'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IctTrainingRoute = IctTrainingRouteImport.update({
  id: '/ict-training',
  path: '/ict-training',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArewagateAirtimeRouteRoute =
  ApiArewagateAirtimeRouteRouteImport.update({
    id: '/api/arewagate/airtime',
    path: '/api/arewagate/airtime',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateBvnVerificationRouteRoute =
  ApiArewagateBvnVerificationRouteRouteImport.update({
    id: '/api/arewagate/bvn-verification',
    path: '/api/arewagate/bvn-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateCacVerificationRouteRoute =
  ApiArewagateCacVerificationRouteRouteImport.update({
    id: '/api/arewagate/cac-verification',
    path: '/api/arewagate/cac-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateNinSlipNormalRouteRoute =
  ApiArewagateNinSlipNormalRouteRouteImport.update({
    id: '/api/arewagate/nin-slip-normal',
    path: '/api/arewagate/nin-slip-normal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateNinSlipPremiumRouteRoute =
  ApiArewagateNinSlipPremiumRouteRouteImport.update({
    id: '/api/arewagate/nin-slip-premium',
    path: '/api/arewagate/nin-slip-premium',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateNinVerificationRouteRoute =
  ApiArewagateNinVerificationRouteRouteImport.update({
    id: '/api/arewagate/nin-verification',
    path: '/api/arewagate/nin-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateNinVerificationSlipRouteRoute =
  ApiArewagateNinVerificationSlipRouteRouteImport.update({
    id: '/api/arewagate/nin-verification-slip',
    path: '/api/arewagate/nin-verification-slip',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateScratchCardRouteRoute =
  ApiArewagateScratchCardRouteRouteImport.update({
    id: '/api/arewagate/scratch-card',
    path: '/api/arewagate/scratch-card',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateTransactionsRouteRoute =
  ApiArewagateTransactionsRouteRouteImport.update({
    id: '/api/arewagate/transactions',
    path: '/api/arewagate/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateWalletRouteRoute = ApiArewagateWalletRouteRouteImport.update({
  id: '/api/arewagate/wallet',
  path: '/api/arewagate/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArewagateDataDetailsRoute = ApiArewagateDataDetailsRouteImport.update({
  id: '/api/arewagate/data/details',
  path: '/api/arewagate/data/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArewagateDataPurchaseRoute =
  ApiArewagateDataPurchaseRouteImport.update({
    id: '/api/arewagate/data/purchase',
    path: '/api/arewagate/data/purchase',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateJambDetailsRoute = ApiArewagateJambDetailsRouteImport.update({
  id: '/api/arewagate/jamb/details',
  path: '/api/arewagate/jamb/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArewagateJambPurchaseRoute =
  ApiArewagateJambPurchaseRouteImport.update({
    id: '/api/arewagate/jamb/purchase',
    path: '/api/arewagate/jamb/purchase',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArewagateScratchCardBalanceRouteRoute =
  ApiArewagateScratchCardBalanceRouteRouteImport.update({
    id: '/balance',
    path: '/balance',
    getParentRoute: () => ApiArewagateScratchCardRouteRoute,
  } as any)
const ApiArewagateUtilityBillsPayRouteRoute =
  ApiArewagateUtilityBillsPayRouteRouteImport.update({
    id: '/api/arewagate/utility-bills/pay',
    path: '/api/arewagate/utility-bills/pay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/ict-training': typeof IctTrainingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/category/$slug': typeof CategorySlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/api/arewagate/airtime': typeof ApiArewagateAirtimeRouteRoute
  '/api/arewagate/bvn-verification': typeof ApiArewagateBvnVerificationRouteRoute
  '/api/arewagate/cac-verification': typeof ApiArewagateCacVerificationRouteRoute
  '/api/arewagate/nin-slip-normal': typeof ApiArewagateNinSlipNormalRouteRoute
  '/api/arewagate/nin-slip-premium': typeof ApiArewagateNinSlipPremiumRouteRoute
  '/api/arewagate/nin-verification': typeof ApiArewagateNinVerificationRouteRoute
  '/api/arewagate/nin-verification-slip': typeof ApiArewagateNinVerificationSlipRouteRoute
  '/api/arewagate/scratch-card': typeof ApiArewagateScratchCardRouteRouteWithChildren
  '/api/arewagate/transactions': typeof ApiArewagateTransactionsRouteRoute
  '/api/arewagate/wallet': typeof ApiArewagateWalletRouteRoute
  '/api/arewagate/scratch-card/balance': typeof ApiArewagateScratchCardBalanceRouteRoute
  '/api/arewagate/utility-bills/pay': typeof ApiArewagateUtilityBillsPayRouteRoute
  '/api/arewagate/data/details': typeof ApiArewagateDataDetailsRoute
  '/api/arewagate/data/purchase': typeof ApiArewagateDataPurchaseRoute
  '/api/arewagate/jamb/details': typeof ApiArewagateJambDetailsRoute
  '/api/arewagate/jamb/purchase': typeof ApiArewagateJambPurchaseRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/ict-training': typeof IctTrainingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/category/$slug': typeof CategorySlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/api/arewagate/airtime': typeof ApiArewagateAirtimeRouteRoute
  '/api/arewagate/bvn-verification': typeof ApiArewagateBvnVerificationRouteRoute
  '/api/arewagate/cac-verification': typeof ApiArewagateCacVerificationRouteRoute
  '/api/arewagate/nin-slip-normal': typeof ApiArewagateNinSlipNormalRouteRoute
  '/api/arewagate/nin-slip-premium': typeof ApiArewagateNinSlipPremiumRouteRoute
  '/api/arewagate/nin-verification': typeof ApiArewagateNinVerificationRouteRoute
  '/api/arewagate/nin-verification-slip': typeof ApiArewagateNinVerificationSlipRouteRoute
  '/api/arewagate/scratch-card': typeof ApiArewagateScratchCardRouteRouteWithChildren
  '/api/arewagate/transactions': typeof ApiArewagateTransactionsRouteRoute
  '/api/arewagate/wallet': typeof ApiArewagateWalletRouteRoute
  '/api/arewagate/scratch-card/balance': typeof ApiArewagateScratchCardBalanceRouteRoute
  '/api/arewagate/utility-bills/pay': typeof ApiArewagateUtilityBillsPayRouteRoute
  '/api/arewagate/data/details': typeof ApiArewagateDataDetailsRoute
  '/api/arewagate/data/purchase': typeof ApiArewagateDataPurchaseRoute
  '/api/arewagate/jamb/details': typeof ApiArewagateJambDetailsRoute
  '/api/arewagate/jamb/purchase': typeof ApiArewagateJambPurchaseRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/ict-training': typeof IctTrainingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/category/$slug': typeof CategorySlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/api/arewagate/airtime': typeof ApiArewagateAirtimeRouteRoute
  '/api/arewagate/bvn-verification': typeof ApiArewagateBvnVerificationRouteRoute
  '/api/arewagate/cac-verification': typeof ApiArewagateCacVerificationRouteRoute
  '/api/arewagate/nin-slip-normal': typeof ApiArewagateNinSlipNormalRouteRoute
  '/api/arewagate/nin-slip-premium': typeof ApiArewagateNinSlipPremiumRouteRoute
  '/api/arewagate/nin-verification': typeof ApiArewagateNinVerificationRouteRoute
  '/api/arewagate/nin-verification-slip': typeof ApiArewagateNinVerificationSlipRouteRoute
  '/api/arewagate/scratch-card': typeof ApiArewagateScratchCardRouteRouteWithChildren
  '/api/arewagate/transactions': typeof ApiArewagateTransactionsRouteRoute
  '/api/arewagate/wallet': typeof ApiArewagateWalletRouteRoute
  '/api/arewagate/scratch-card/balance': typeof ApiArewagateScratchCardBalanceRouteRoute
  '/api/arewagate/utility-bills/pay': typeof ApiArewagateUtilityBillsPayRouteRoute
  '/api/arewagate/data/details': typeof ApiArewagateDataDetailsRoute
  '/api/arewagate/data/purchase': typeof ApiArewagateDataPurchaseRoute
  '/api/arewagate/jamb/details': typeof ApiArewagateJambDetailsRoute
  '/api/arewagate/jamb/purchase': typeof ApiArewagateJambPurchaseRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/ict-training'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/shop'
    | '/terms'
    | '/track'
    | '/admin'
    | '/dashboard'
    | '/orders'
    | '/wallet'
    | '/category/$slug'
    | '/service/$slug'
    | '/api/arewagate/airtime'
    | '/api/arewagate/bvn-verification'
    | '/api/arewagate/cac-verification'
    | '/api/arewagate/nin-slip-normal'
    | '/api/arewagate/nin-slip-premium'
    | '/api/arewagate/nin-verification'
    | '/api/arewagate/nin-verification-slip'
    | '/api/arewagate/scratch-card'
    | '/api/arewagate/transactions'
    | '/api/arewagate/wallet'
    | '/api/arewagate/scratch-card/balance'
    | '/api/arewagate/utility-bills/pay'
    | '/api/arewagate/data/details'
    | '/api/arewagate/data/purchase'
    | '/api/arewagate/jamb/details'
    | '/api/arewagate/jamb/purchase'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/ict-training'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/shop'
    | '/terms'
    | '/track'
    | '/admin'
    | '/dashboard'
    | '/orders'
    | '/wallet'
    | '/category/$slug'
    | '/service/$slug'
    | '/api/arewagate/airtime'
    | '/api/arewagate/bvn-verification'
    | '/api/arewagate/cac-verification'
    | '/api/arewagate/nin-slip-normal'
    | '/api/arewagate/nin-slip-premium'
    | '/api/arewagate/nin-verification'
    | '/api/arewagate/nin-verification-slip'
    | '/api/arewagate/scratch-card'
    | '/api/arewagate/transactions'
    | '/api/arewagate/wallet'
    | '/api/arewagate/scratch-card/balance'
    | '/api/arewagate/utility-bills/pay'
    | '/api/arewagate/data/details'
    | '/api/arewagate/data/purchase'
    | '/api/arewagate/jamb/details'
    | '/api/arewagate/jamb/purchase'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/ict-training'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/shop'
    | '/terms'
    | '/track'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/wallet'
    | '/category/$slug'
    | '/service/$slug'
    | '/api/arewagate/airtime'
    | '/api/arewagate/bvn-verification'
    | '/api/arewagate/cac-verification'
    | '/api/arewagate/nin-slip-normal'
    | '/api/arewagate/nin-slip-premium'
    | '/api/arewagate/nin-verification'
    | '/api/arewagate/nin-verification-slip'
    | '/api/arewagate/scratch-card'
    | '/api/arewagate/transactions'
    | '/api/arewagate/wallet'
    | '/api/arewagate/scratch-card/balance'
    | '/api/arewagate/utility-bills/pay'
    | '/api/arewagate/data/details'
    | '/api/arewagate/data/purchase'
    | '/api/arewagate/jamb/details'
    | '/api/arewagate/jamb/purchase'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  IctTrainingRoute: typeof IctTrainingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  ApiArewagateAirtimeRouteRoute: typeof ApiArewagateAirtimeRouteRoute
  ApiArewagateBvnVerificationRouteRoute: typeof ApiArewagateBvnVerificationRouteRoute
  ApiArewagateCacVerificationRouteRoute: typeof ApiArewagateCacVerificationRouteRoute
  ApiArewagateNinSlipNormalRouteRoute: typeof ApiArewagateNinSlipNormalRouteRoute
  ApiArewagateNinSlipPremiumRouteRoute: typeof ApiArewagateNinSlipPremiumRouteRoute
  ApiArewagateNinVerificationRouteRoute: typeof ApiArewagateNinVerificationRouteRoute
  ApiArewagateNinVerificationSlipRouteRoute: typeof ApiArewagateNinVerificationSlipRouteRoute
  ApiArewagateScratchCardRouteRoute: typeof ApiArewagateScratchCardRouteRouteWithChildren
  ApiArewagateTransactionsRouteRoute: typeof ApiArewagateTransactionsRouteRoute
  ApiArewagateWalletRouteRoute: typeof ApiArewagateWalletRouteRoute
  ApiArewagateUtilityBillsPayRouteRoute: typeof ApiArewagateUtilityBillsPayRouteRoute
  ApiArewagateDataDetailsRoute: typeof ApiArewagateDataDetailsRoute
  ApiArewagateDataPurchaseRoute: typeof ApiArewagateDataPurchaseRoute
  ApiArewagateJambDetailsRoute: typeof ApiArewagateJambDetailsRoute
  ApiArewagateJambPurchaseRoute: typeof ApiArewagateJambPurchaseRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ict-training': {
      id: '/ict-training'
      path: '/ict-training'
      fullPath: '/ict-training'
      preLoaderRoute: typeof IctTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/airtime': {
      id: '/api/arewagate/airtime'
      path: '/api/arewagate/airtime'
      fullPath: '/api/arewagate/airtime'
      preLoaderRoute: typeof ApiArewagateAirtimeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/bvn-verification': {
      id: '/api/arewagate/bvn-verification'
      path: '/api/arewagate/bvn-verification'
      fullPath: '/api/arewagate/bvn-verification'
      preLoaderRoute: typeof ApiArewagateBvnVerificationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/cac-verification': {
      id: '/api/arewagate/cac-verification'
      path: '/api/arewagate/cac-verification'
      fullPath: '/api/arewagate/cac-verification'
      preLoaderRoute: typeof ApiArewagateCacVerificationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/nin-slip-normal': {
      id: '/api/arewagate/nin-slip-normal'
      path: '/api/arewagate/nin-slip-normal'
      fullPath: '/api/arewagate/nin-slip-normal'
      preLoaderRoute: typeof ApiArewagateNinSlipNormalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/nin-slip-premium': {
      id: '/api/arewagate/nin-slip-premium'
      path: '/api/arewagate/nin-slip-premium'
      fullPath: '/api/arewagate/nin-slip-premium'
      preLoaderRoute: typeof ApiArewagateNinSlipPremiumRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/nin-verification': {
      id: '/api/arewagate/nin-verification'
      path: '/api/arewagate/nin-verification'
      fullPath: '/api/arewagate/nin-verification'
      preLoaderRoute: typeof ApiArewagateNinVerificationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/nin-verification-slip': {
      id: '/api/arewagate/nin-verification-slip'
      path: '/api/arewagate/nin-verification-slip'
      fullPath: '/api/arewagate/nin-verification-slip'
      preLoaderRoute: typeof ApiArewagateNinVerificationSlipRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/scratch-card': {
      id: '/api/arewagate/scratch-card'
      path: '/api/arewagate/scratch-card'
      fullPath: '/api/arewagate/scratch-card'
      preLoaderRoute: typeof ApiArewagateScratchCardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/transactions': {
      id: '/api/arewagate/transactions'
      path: '/api/arewagate/transactions'
      fullPath: '/api/arewagate/transactions'
      preLoaderRoute: typeof ApiArewagateTransactionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/wallet': {
      id: '/api/arewagate/wallet'
      path: '/api/arewagate/wallet'
      fullPath: '/api/arewagate/wallet'
      preLoaderRoute: typeof ApiArewagateWalletRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/data/details': {
      id: '/api/arewagate/data/details'
      path: '/api/arewagate/data/details'
      fullPath: '/api/arewagate/data/details'
      preLoaderRoute: typeof ApiArewagateDataDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/data/purchase': {
      id: '/api/arewagate/data/purchase'
      path: '/api/arewagate/data/purchase'
      fullPath: '/api/arewagate/data/purchase'
      preLoaderRoute: typeof ApiArewagateDataPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/jamb/details': {
      id: '/api/arewagate/jamb/details'
      path: '/api/arewagate/jamb/details'
      fullPath: '/api/arewagate/jamb/details'
      preLoaderRoute: typeof ApiArewagateJambDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/jamb/purchase': {
      id: '/api/arewagate/jamb/purchase'
      path: '/api/arewagate/jamb/purchase'
      fullPath: '/api/arewagate/jamb/purchase'
      preLoaderRoute: typeof ApiArewagateJambPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arewagate/scratch-card/balance': {
      id: '/api/arewagate/scratch-card/balance'
      path: '/balance'
      fullPath: '/api/arewagate/scratch-card/balance'
      preLoaderRoute: typeof ApiArewagateScratchCardBalanceRouteRouteImport
      parentRoute: typeof ApiArewagateScratchCardRouteRoute
    }
    '/api/arewagate/utility-bills/pay': {
      id: '/api/arewagate/utility-bills/pay'
      path: '/api/arewagate/utility-bills/pay'
      fullPath: '/api/arewagate/utility-bills/pay'
      preLoaderRoute: typeof ApiArewagateUtilityBillsPayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiArewagateScratchCardRouteRouteChildren {
  ApiArewagateScratchCardBalanceRouteRoute: typeof ApiArewagateScratchCardBalanceRouteRoute
}

const ApiArewagateScratchCardRouteRouteChildren: ApiArewagateScratchCardRouteRouteChildren =
  {
    ApiArewagateScratchCardBalanceRouteRoute:
      ApiArewagateScratchCardBalanceRouteRoute,
  }

const ApiArewagateScratchCardRouteRouteWithChildren =
  ApiArewagateScratchCardRouteRoute._addFileChildren(
    ApiArewagateScratchCardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  IctTrainingRoute: IctTrainingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  CategorySlugRoute: CategorySlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  ApiArewagateAirtimeRouteRoute: ApiArewagateAirtimeRouteRoute,
  ApiArewagateBvnVerificationRouteRoute: ApiArewagateBvnVerificationRouteRoute,
  ApiArewagateCacVerificationRouteRoute: ApiArewagateCacVerificationRouteRoute,
  ApiArewagateNinSlipNormalRouteRoute: ApiArewagateNinSlipNormalRouteRoute,
  ApiArewagateNinSlipPremiumRouteRoute: ApiArewagateNinSlipPremiumRouteRoute,
  ApiArewagateNinVerificationRouteRoute: ApiArewagateNinVerificationRouteRoute,
  ApiArewagateNinVerificationSlipRouteRoute:
    ApiArewagateNinVerificationSlipRouteRoute,
  ApiArewagateScratchCardRouteRoute:
    ApiArewagateScratchCardRouteRouteWithChildren,
  ApiArewagateTransactionsRouteRoute: ApiArewagateTransactionsRouteRoute,
  ApiArewagateWalletRouteRoute: ApiArewagateWalletRouteRoute,
  ApiArewagateUtilityBillsPayRouteRoute: ApiArewagateUtilityBillsPayRouteRoute,
  ApiArewagateDataDetailsRoute: ApiArewagateDataDetailsRoute,
  ApiArewagateDataPurchaseRoute: ApiArewagateDataPurchaseRoute,
  ApiArewagateJambDetailsRoute: ApiArewagateJambDetailsRoute,
  ApiArewagateJambPurchaseRoute: ApiArewagateJambPurchaseRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
